#Database
POSTGRES_SQL_USERNAME: postgres
POSTGRES_SQL_PASSWORD: Simba2018!
POSTGRES_SQL_HOST: 192.168.1.216
#POSTGRES_SQL_HOST: localhost
POSTGRES_SQL_PORT: 5432
POSTGRES_SQL_DB: evo_apartments

#Server
SERVER_PORT: 9000
ACTIVE_PROFILE: dev