#Database
POSTGRES_SQL_USERNAME:
POSTGRES_SQL_PASSWORD:
POSTGRES_SQL_HOST:
POSTGRES_SQL_PORT:
POSTGRES_SQL_DB:

#Server
SERVER_PORT: 7000
ACTIVE_PROFILE: test

#Email
EMAIL_HOST: smtp.gmail.com
EMAIL_PORT: 587
EMAIL_ID: <EMAIL ADDRESS>
EMAIL_PASSWORD: <EMAIL ADDRESS>
VERIFY_EMAIL_HOST: http://localhost:${SERVER_PORT}